import { MigrationInterface, QueryRunner } from "typeorm";

export class GameEntities1721153255178 implements MigrationInterface {
    name = 'GameEntities1721153255178'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "slug" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "slug" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "title" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "summary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "summary" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "post" ADD "body" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lecture" ALTER COLUMN "slug" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lecture" ALTER COLUMN "slug" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "lecture" ALTER COLUMN "title" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lecture" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "lecture" ALTER COLUMN "summary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lecture" ALTER COLUMN "summary" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "lecture" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "lecture" ADD "body" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chapter" ALTER COLUMN "slug" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chapter" ALTER COLUMN "slug" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "chapter" ALTER COLUMN "title" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chapter" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "chapter" ALTER COLUMN "summary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chapter" ALTER COLUMN "summary" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "chapter" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "chapter" ADD "body" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "slug" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "slug" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "title" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "summary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "summary" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "course" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "course" ADD "body" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "slug" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "slug" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "title" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "summary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "summary" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "proposal" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "proposal" ADD "body" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "slug" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "slug" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "title" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "summary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "summary" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "game_version" DROP COLUMN "version"`);
        await queryRunner.query(`ALTER TABLE "game_version" ADD "version" character varying(64) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game_version" DROP COLUMN "archive_url"`);
        await queryRunner.query(`ALTER TABLE "game_version" ADD "archive_url" character varying(1024) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game_version" DROP COLUMN "notes_url"`);
        await queryRunner.query(`ALTER TABLE "game_version" ADD "notes_url" character varying(1024) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game_version" DROP COLUMN "feedback_form"`);
        await queryRunner.query(`ALTER TABLE "game_version" ADD "feedback_form" character varying(1024) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game" ALTER COLUMN "slug" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game" ALTER COLUMN "slug" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "game" ALTER COLUMN "title" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "game" ALTER COLUMN "summary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game" ALTER COLUMN "summary" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "game" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "game" ADD "body" text NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cd1bddce36edc3e766798eab37" ON "post" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_e28aa0c4114146bfb1567bfa9a" ON "post" ("title") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_dff3c45c6a2688bdef948f158a" ON "lecture" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c8c4ea44b8a5a5c6a028b9e20" ON "lecture" ("title") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0c24da73936f0eb347e9835b4f" ON "chapter" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_1540f666b7a73b75b2c13e5db2" ON "chapter" ("title") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a101f48e5045bcf501540a4a5b" ON "course" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac5edecc1aefa58ed0237a7ee4" ON "course" ("title") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_894de7603d8172deb20277c6f5" ON "proposal" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_175c19011e5f5baf732945a311" ON "proposal" ("title") `);
        await queryRunner.query(`CREATE INDEX "IDX_53d4ec636b3f0119f63a20cad8" ON "game_version" ("feedback_deadline") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b9af94cf126ec9f9b2e3523736" ON "game" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_0152ed47a9e8963b5aaceb51e7" ON "game" ("title") `);
        await queryRunner.query(`ALTER TABLE "game_version" ADD CONSTRAINT "UQ_9231b15cd2768c08bc08b464042" UNIQUE ("version", "game_id")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "game_version" DROP CONSTRAINT "UQ_9231b15cd2768c08bc08b464042"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0152ed47a9e8963b5aaceb51e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9af94cf126ec9f9b2e3523736"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53d4ec636b3f0119f63a20cad8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_175c19011e5f5baf732945a311"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_894de7603d8172deb20277c6f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac5edecc1aefa58ed0237a7ee4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a101f48e5045bcf501540a4a5b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1540f666b7a73b75b2c13e5db2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c24da73936f0eb347e9835b4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c8c4ea44b8a5a5c6a028b9e20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dff3c45c6a2688bdef948f158a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e28aa0c4114146bfb1567bfa9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd1bddce36edc3e766798eab37"`);
        await queryRunner.query(`ALTER TABLE "game" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "game" ADD "body" jsonb DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "game" ALTER COLUMN "summary" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "game" ALTER COLUMN "summary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game" ALTER COLUMN "title" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "game" ALTER COLUMN "title" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game" ALTER COLUMN "slug" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "game" ALTER COLUMN "slug" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game_version" DROP COLUMN "feedback_form"`);
        await queryRunner.query(`ALTER TABLE "game_version" ADD "feedback_form" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game_version" DROP COLUMN "notes_url"`);
        await queryRunner.query(`ALTER TABLE "game_version" ADD "notes_url" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game_version" DROP COLUMN "archive_url"`);
        await queryRunner.query(`ALTER TABLE "game_version" ADD "archive_url" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "game_version" DROP COLUMN "version"`);
        await queryRunner.query(`ALTER TABLE "game_version" ADD "version" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "summary" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "summary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "title" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "title" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "slug" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "slug" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "proposal" ADD "body" jsonb DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "summary" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "summary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "title" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "title" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "slug" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "proposal" ALTER COLUMN "slug" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "course" ADD "body" jsonb DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "summary" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "summary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "title" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "title" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "slug" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "course" ALTER COLUMN "slug" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chapter" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "chapter" ADD "body" jsonb DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "chapter" ALTER COLUMN "summary" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "chapter" ALTER COLUMN "summary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chapter" ALTER COLUMN "title" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "chapter" ALTER COLUMN "title" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "chapter" ALTER COLUMN "slug" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "chapter" ALTER COLUMN "slug" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lecture" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "lecture" ADD "body" jsonb DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "lecture" ALTER COLUMN "summary" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "lecture" ALTER COLUMN "summary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lecture" ALTER COLUMN "title" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "lecture" ALTER COLUMN "title" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "lecture" ALTER COLUMN "slug" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "lecture" ALTER COLUMN "slug" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "post" ADD "body" jsonb DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "summary" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "summary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "title" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "title" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "slug" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "post" ALTER COLUMN "slug" DROP NOT NULL`);
    }

}
