// <auto-generated />
[assembly: global::GameGuild.UseCaseEventContractAttribute(typeof(global::GameGuild.Announcements.Contracts.AnnouncePublicationCommand), "announcements.contracts.announce-publication", NoDomainEventReason = "No named cross-module event is declared; the durable generic operation event remains the observable contract.")]
