// <auto-generated />
[assembly: global::GameGuild.UseCaseEventContractAttribute(typeof(global::GameGuild.API.Eventing.ReplayOutboxEventCommand), "api.replay-outbox-event", NoDomainEventReason = "No named cross-module event is declared; the durable generic operation event remains the observable contract.")]
