name: ðŸž Bug Report
description: "File a new bug report."
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > **Please ensure you are using the latest version of GameGuild before submitting an issue, as the bug may have already been fixed in a recent update.** (Of course, if you're experiencing an issue on the latest version that wasn't present in a previous version, please let us know.)

        # ðŸ’Ž Bounty Program (with [algora.io](https://console.algora.io/org/GameGuild/bounties/new))
          - If you would like to prioritize the issue resolution, consider adding a bounty to this issue through our [Bounty Program](https://console.algora.io/org/GameGuild/bounties/new).

  - type: textarea
    attributes:
      label: Error Message, Logs or Screenshots
      description: Provide a detailed description of the error or exception you encountered, along with any relevant log output.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please provide a step-by-step guide to reproduce the issue. Be as detailed as possible, otherwise we may not be able to assist you. Record videos or GIFs if necessary or easier.
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: input
    attributes:
      label: Example URL
      description: If applicable, provide a URL to a repository demonstrating the issue. Or the main route URL where the issue occurs.

  - type: input
    attributes:
      label: GameGuild Version
      description: Please provide the GameGuild version you are using. This can be found in the top left corner of your GameGuild dashboard.
      placeholder: "v4.0.0-beta.335"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Are you using GameGuild Cloud?
      options:
        - "No (self-hosted)"
        - "Yes (GameGuild Cloud)"
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System and Version (self-hosted)
      description: Run `cat /etc/os-release` or `lsb_release -a` in your terminal and provide the operating system and version.
      placeholder: "Ubuntu 22.04"

  - type: textarea
    attributes:
      label: Additional Information
      description: Any other relevant details about the issue.