using GameGuild;
using GameGuild.Learning.Experience.Social;

[assembly: UseCaseEventContract(typeof(CreateDiscussionCommand), "learning-social.discussion.create", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(PinDiscussionCommand), "learning-social.discussion.pin", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(UnpinDiscussionCommand), "learning-social.discussion.unpin", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(MarkDiscussionResolvedCommand), "learning-social.discussion.resolve", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(DeleteDiscussionCommand), "learning-social.discussion.delete", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(GenerateFeedItemsCommand), "learning-social.feed.generate", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(MarkFeedItemViewedCommand), "learning-social.feed-item.view", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(DismissFeedItemCommand), "learning-social.feed-item.dismiss", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(LikeCourseCommand), "learning-social.course.like", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(UnlikeCourseCommand), "learning-social.course.unlike", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(CreateReplyCommand), "learning-social.reply.create", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(AcceptReplyAsAnswerCommand), "learning-social.reply.accept-answer", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(UpvoteReplyCommand), "learning-social.reply.upvote", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(DeleteReplyCommand), "learning-social.reply.delete", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(CreateReviewCommand), "learning-social.review.create", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(MarkReviewHelpfulCommand), "learning-social.review.mark-helpful", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(DeleteReviewCommand), "learning-social.review.delete", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(ApproveReviewCommand), "learning-social.review.approve", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(FeatureReviewCommand), "learning-social.review.feature", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(UpdateReviewModerationCommand), "learning-social.review.update-moderation", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(AddToWishlistCommand), "learning-social.wishlist.add", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(RemoveFromWishlistCommand), "learning-social.wishlist.remove", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
[assembly: UseCaseEventContract(typeof(UpdateWishlistPreferencesCommand), "learning-social.wishlist.update-preferences", NoDomainEventReason = "The legacy social aggregate currently emits the generic durable operation event only.")]
