# FROM riscv64/alpine:3.21
FROM alpine:3.21

# install gcc compiler
# RUN apk add --no-cache build-base

# Install clang and other necessary development tools
RUN apk add --no-cache \
    clang \
    llvm \
    lld \
    musl-dev \
    libc-dev \
    make \
    cmake \
    binutils

VOLUME /project
WORKDIR /project
