// <auto-generated />
using System;
using cms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace cms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250603143200_MakeResourceBaseTenantable")]
    partial class MakeResourceBaseTenantable
    {
        /// <summary>
        /// Builds the target model for this migration
        /// </summary>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0");

            // Model definitions will be auto-generated when running the actual migration
#pragma warning restore 612, 618
        }
    }
}
