// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cms.Data;

#nullable disable

namespace cms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250605100321_RefactorInheritanceFromTPTToTPC")]
    partial class RefactorInheritanceFromTPTToTPC
    {
        // Designer file is auto-generated when the migration is created via EF CLI
        // Since we're creating this manually, we'll leave the implementation empty
        // The target model will be built by Entity Framework at runtime
    }
}
