<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
      <ProjectReference Include="..\GameGuild.Announcements.Contracts\GameGuild.Announcements.Contracts.csproj" />
</ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="GameGuild.Learning.Courses.UnitTests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GameGuild.SharedKernel\GameGuild.SharedKernel.csproj" />
        <ProjectReference Include="..\GameGuild.Identity.Authentication\GameGuild.Identity.Authentication.csproj" />
        <ProjectReference Include="..\GameGuild.Identity.Authorization\GameGuild.Identity.Authorization.csproj" />
        <ProjectReference Include="..\GameGuild.Identity.Users\GameGuild.Identity.Users.csproj" />
        <ProjectReference Include="..\GameGuild.Commerce.Products\GameGuild.Commerce.Products.csproj" />
        <ProjectReference Include="..\GameGuild.Tags\GameGuild.Tags.csproj" />
        <ProjectReference Include="..\GameGuild.Learning\GameGuild.Learning.csproj" />
        <ProjectReference Include="..\GameGuild.Notifications\GameGuild.Notifications.csproj" />
        <ProjectReference Include="..\GameGuild.AI\GameGuild.AI.csproj" />
        <ProjectReference Include="..\GameGuild.Finance.Economy\GameGuild.Finance.Economy.csproj" />
    </ItemGroup>

</Project>
