mindmap
  root((crypto games))
    Marketplace
      Auction House
      Buy and Sell at price
    Crypto Abstracton Layer
      Managed Wallets
      CEX
        Accept cedit card
      DEX
        Convert fudiciary tokens
    InApp Purchases
      Consumable
      Non-Consumable
      Recurrent Payment
    Wallets
      Tokens
        Items NFT
        Fungible
          Hard Coins
          Soft Coins
        DAO Governance
          Ordinary
          Preferred
    Tools
      Contract Interfacing
      Analytics
      Plugins
        Unity
        Godot
        Unreal