mindmap
  root((networking))
    Cloud Services
      Lobby
      Matchmaking
      Rooms
    Discovery
      TURN / Circuit Relay
      STUN / NAT Punch
      MDNS
      DHT
      Directory of Nodes
    Protocols
      UDP
        Reliable
        Unreliable
      TCP
    Messaging
      Pub/Sub
      Target
        Broadcast
        Unicast
      Types
        RPC
        Events
        Commands
        State
    Transport
      QUIC
      WebRTC
      WebSocket
    SDKs
      Strategies
        Non Deterministic
          State Synchronization
          Interpolation
          Prediction / Extrapolation
          Lag Compensation
        Deterministic
          Fixed-Lockstep
          Predict Rollback Physics
      Engines
        Unity
        Unreal
        Godot