Table chapter_editors_user {
  chapter_id uuid
  user_id uuid
}

Table ChapterEntity {
  body text
  course CourseEntity
  createdAt timestamp
  id uuid
  order float
  owner UserEntity
  slug varchar
  summary string
  thumbnail ImageEntity
  title varchar
  updatedAt timestamp
  visibility enum
  editors UserEntity
  lectures LectureEntity
}

Table CompetitionMatchEntity {
  createdAt timestamp
  id uuid
  lastState text
  logs text
  p1cpuTime float4
  p1Points float
  p1submission CompetitionSubmissionEntity
  p1Turns integer
  p2cpuTime float4
  p2Points float
  p2submission CompetitionSubmissionEntity
  p2Turns integer
  run CompetitionRunEntity
  updatedAt timestamp
  winner enum
}

Table CompetitionRunEntity {
  createdAt timestamp
  gameType string
  id uuid
  state enum
  updatedAt timestamp
  matches CompetitionMatchEntity
  reports CompetitionRunSubmissionReportEntity
}

Table CompetitionRunSubmissionReportEntity {
  createdAt timestamp
  id uuid
  pointsAsP1 float8
  pointsAsP2 float8
  run CompetitionRunEntity
  submission CompetitionSubmissionEntity
  totalPoints float8
  totalWins integer
  updatedAt timestamp
  user UserEntity
  winsAsP1 integer
  winsAsP2 integer
}

Table CompetitionSubmissionEntity {
  createdAt timestamp
  executable bytea
  gameType enum
  id uuid
  sourceCodeZip bytea
  updatedAt timestamp
  user UserEntity
  matchesAsP1 CompetitionMatchEntity
  matchesAsP2 CompetitionMatchEntity
  submissionReports CompetitionRunSubmissionReportEntity
}

Table course_editors_user {
  course_id uuid
  user_id uuid
}

Table CourseEntity {
  body text
  createdAt timestamp
  id uuid
  owner UserEntity
  price decimal
  slug varchar
  subscriptionAccess boolean
  summary string
  thumbnail ImageEntity
  title varchar
  updatedAt timestamp
  visibility enum
  chapters ChapterEntity
  editors UserEntity
  lectures LectureEntity
}

Table EventEntity {
  body text
  createdAt timestamp
  id uuid
  owner UserEntity
  slug varchar
  summary string
  thumbnail ImageEntity
  title varchar
  updatedAt timestamp
  visibility enum
  editors UserEntity
}

Table ImageEntity {
  createdAt timestamp
  description string
  filename string
  hash string
  height integer
  id uuid
  mimetype string
  originalFilename string
  path string
  sizeBytes integer
  source string
  updatedAt timestamp
  width integer
}

Table job_post_editors_user {
  job_post_id uuid
  user_id uuid
}

Table job_post_job_tags_job_tag {
  job_post_id uuid
  job_tag_id uuid
}

Table JobApplicationEntity {
  applicant UserEntity
  createdAt timestamp
  id uuid
  job JobPostEntity
  progress integer
  rejected boolean
  updatedAt timestamp
  withdrawn boolean
}

Table JobPostEntity {
  body text
  createdAt timestamp
  id uuid
  job_type enum
  location varchar
  owner UserEntity
  slug varchar
  summary string
  thumbnail ImageEntity
  title varchar
  updatedAt timestamp
  visibility enum
  editors UserEntity
  job_tags JobTagEntity
}

Table JobTagEntity {
  createdAt timestamp
  id uuid
  name varchar
  updatedAt timestamp
}

Table lecture_editors_user {
  lecture_id uuid
  user_id uuid
}

Table LectureEntity {
  body text
  chapter ChapterEntity
  course CourseEntity
  createdAt timestamp
  id uuid
  json jsonb
  order float
  owner UserEntity
  renderer enum
  slug varchar
  summary string
  thumbnail ImageEntity
  title varchar
  updatedAt timestamp
  visibility enum
  editors UserEntity
}

Table post_editors_user {
  post_id uuid
  user_id uuid
}

Table PostEntity {
  body text
  createdAt timestamp
  id uuid
  owner UserEntity
  PostType enum
  slug varchar
  summary string
  thumbnail ImageEntity
  title varchar
  updatedAt timestamp
  visibility enum
  editors UserEntity
}

Table project_editors_user {
  project_id uuid
  user_id uuid
}

Table project_screenshots_images {
  images_id uuid
  project_id uuid
}

Table ProjectEntity {
  banner ImageEntity
  body text
  createdAt timestamp
  id uuid
  owner UserEntity
  slug varchar
  summary string
  thumbnail ImageEntity
  title varchar
  updatedAt timestamp
  visibility enum
  editors UserEntity
  screenshots ImageEntity
  tickets TicketEntity
  versions ProjectVersionEntity
}

Table ProjectFeedbackResponseEntity {
  createdAt timestamp
  id uuid
  responses jsonb
  updatedAt timestamp
  user UserEntity
  version ProjectVersionEntity
}

Table ProjectVersionEntity {
  archive_url string
  createdAt timestamp
  feedback_deadline timestamptz
  feedback_form jsonb
  id uuid
  notes_url string
  project ProjectEntity
  updatedAt timestamp
  version string
  responses ProjectFeedbackResponseEntity
}

Table proposal_editors_user {
  proposal_id uuid
  user_id uuid
}

Table ProposalEntity {
  body text
  createdAt timestamp
  id uuid
  owner UserEntity
  slug varchar
  summary string
  thumbnail ImageEntity
  title varchar
  updatedAt timestamp
  visibility enum
  editors UserEntity
}

Table quiz_editors_user {
  quiz_id uuid
  user_id uuid
}

Table QuizEntity {
  body text
  createdAt timestamp
  gradingInstructions string
  id uuid
  owner UserEntity
  questions jsonb
  slug varchar
  summary string
  thumbnail ImageEntity
  title varchar
  updatedAt timestamp
  visibility enum
  editors UserEntity
}

Table TagEntity {
  createdAt timestamp
  id uuid
  tag string
  updatedAt timestamp
}

Table ticket_editors_user {
  ticket_id uuid
  user_id uuid
}

Table TicketEntity {
  createdAt timestamp
  description text
  id uuid
  owner UserEntity
  priority enum
  projectId uuid
  status enum
  title varchar
  updatedAt timestamp
  editors UserEntity
  project ProjectEntity
}

Table UserEntity {
  appleId string
  createdAt timestamp
  elo float
  email varchar
  emailVerified boolean
  facebookId string
  githubId string
  googleId string
  id uuid
  linkedinId string
  passwordHash string
  passwordSalt string
  profile UserProfileEntity
  twitterId string
  updatedAt timestamp
  username varchar
  walletAddress string
  competitionSubmissions CompetitionSubmissionEntity
}

Table UserProfileEntity {
  bio varchar
  createdAt timestamp
  familyName varchar
  givenName varchar
  id uuid
  name varchar
  picture ImageEntity
  updatedAt timestamp
  user UserEntity
}

Table VoteEntity {
  createdAt timestamp
  id uuid
  updatedAt timestamp
}

Ref: ChapterEntity.course > CourseEntity.chapters
Ref: ChapterEntity.editors <> UserEntity.id
Ref: ChapterEntity.lectures < LectureEntity.chapter
Ref: ChapterEntity.owner > UserEntity.id
Ref: ChapterEntity.thumbnail > ImageEntity.id
Ref: CompetitionMatchEntity.p1submission > CompetitionSubmissionEntity.matchesAsP1
Ref: CompetitionMatchEntity.p2submission > CompetitionSubmissionEntity.matchesAsP2
Ref: CompetitionMatchEntity.run > CompetitionRunEntity.matches
Ref: CompetitionRunEntity.reports < CompetitionRunSubmissionReportEntity.run
Ref: CompetitionRunSubmissionReportEntity.submission > CompetitionSubmissionEntity.submissionReports
Ref: CompetitionRunSubmissionReportEntity.user > UserEntity.id
Ref: CompetitionSubmissionEntity.user > UserEntity.competitionSubmissions
Ref: CourseEntity.editors <> UserEntity.id
Ref: CourseEntity.lectures < LectureEntity.course
Ref: CourseEntity.owner > UserEntity.id
Ref: CourseEntity.thumbnail > ImageEntity.id
Ref: EventEntity.editors <> UserEntity.id
Ref: EventEntity.owner > UserEntity.id
Ref: EventEntity.thumbnail > ImageEntity.id
Ref: JobApplicationEntity.applicant > UserEntity.id
Ref: JobApplicationEntity.job > JobPostEntity.id
Ref: JobPostEntity.editors <> UserEntity.id
Ref: JobPostEntity.job_tags <> JobTagEntity.id
Ref: JobPostEntity.owner > UserEntity.id
Ref: JobPostEntity.thumbnail > ImageEntity.id
Ref: LectureEntity.editors <> UserEntity.id
Ref: LectureEntity.owner > UserEntity.id
Ref: LectureEntity.thumbnail > ImageEntity.id
Ref: PostEntity.editors <> UserEntity.id
Ref: PostEntity.owner > UserEntity.id
Ref: PostEntity.thumbnail > ImageEntity.id
Ref: ProjectEntity.banner > ImageEntity.id
Ref: ProjectEntity.editors <> UserEntity.id
Ref: ProjectEntity.owner > UserEntity.id
Ref: ProjectEntity.screenshots <> ImageEntity.id
Ref: ProjectEntity.thumbnail > ImageEntity.id
Ref: ProjectEntity.tickets < TicketEntity.project
Ref: ProjectEntity.versions < ProjectVersionEntity.project
Ref: ProjectFeedbackResponseEntity.user > UserEntity.id
Ref: ProjectFeedbackResponseEntity.version > ProjectVersionEntity.responses
Ref: ProposalEntity.editors <> UserEntity.id
Ref: ProposalEntity.owner > UserEntity.id
Ref: ProposalEntity.thumbnail > ImageEntity.id
Ref: QuizEntity.editors <> UserEntity.id
Ref: QuizEntity.owner > UserEntity.id
Ref: QuizEntity.thumbnail > ImageEntity.id
Ref: TicketEntity.editors <> UserEntity.id
Ref: TicketEntity.owner > UserEntity.id
Ref: UserEntity.profile - UserProfileEntity.user
Ref: UserProfileEntity.picture - ImageEntity.id
